(function () {
  'use strict';
  var token = sessionStorage.getItem('cml_admin_token') || '';
  var username = sessionStorage.getItem('cml_admin_username') || '';
  var login = document.getElementById('login'), dashboard = document.getElementById('dashboard');
  function escapeHtml(value) { var d = document.createElement('div'); d.textContent = value == null ? '' : String(value); return d.innerHTML; }
  function renderList(id, rows) { document.getElementById(id).innerHTML = rows.length ? rows.map(function (r) { return '<div class="rank"><span>' + escapeHtml(r.label) + '</span><b>' + Number(r.count).toLocaleString() + '</b></div>'; }).join('') : '<p class="empty">No traffic yet.</p>'; }
  function countryLabel(code) { var names = { PK: 'Pakistan', GB: 'United Kingdom', US: 'United States', CA: 'Canada', CH: 'Switzerland', DE: 'Germany', AE: 'United Arab Emirates', SA: 'Saudi Arabia', IN: 'India', AU: 'Australia', FR: 'France', IT: 'Italy', ES: 'Spain', NL: 'Netherlands', SE: 'Sweden', NO: 'Norway', TR: 'Turkey', BR: 'Brazil', MX: 'Mexico', ID: 'Indonesia', BD: 'Bangladesh' }; var key = String(code || '').toUpperCase(); return names[key] || key; }
  function renderCountries(rows) { document.getElementById('countries').innerHTML = rows.length ? rows.map(function (r) { return '<div class="rank"><span>' + escapeHtml(countryLabel(r.label)) + '</span><b>' + Number(r.count).toLocaleString() + '</b></div>'; }).join('') : '<p class="empty">No traffic yet.</p>'; }
  function renderTimeline(rows) { var max = Math.max.apply(null, rows.map(function (r) { return Number(r.count); }).concat([1])); document.getElementById('timeline').innerHTML = rows.length ? rows.map(function (r) { var label = r.label.length === 10 ? r.label.slice(5) : r.label.slice(11); return '<div class="bar-wrap" title="' + escapeHtml(r.label) + ': ' + r.count + '"><div class="bar" style="height:' + Math.max(5, Math.round(r.count / max * 150)) + 'px"></div><span>' + escapeHtml(label) + '</span></div>'; }).join('') : '<p class="empty">No traffic yet.</p>'; }
  function renderLive(rows) { document.getElementById('liveRows').innerHTML = rows.length ? rows.map(function (r) { return '<tr><td>' + escapeHtml(r.country) + '</td><td>' + escapeHtml(r.source) + '</td><td>' + escapeHtml(r.device || 'Unknown') + '</td><td>' + escapeHtml(r.browser || 'Unknown') + '</td><td>' + new Date(r.last_seen).toLocaleTimeString() + '</td></tr>'; }).join('') : '<tr><td colspan="5" class="empty">No visitors online.</td></tr>'; }
  function authHeaders() { return { Authorization: 'Bearer ' + token, 'X-Admin-Username': username }; }
  function formatBytes(bytes) { return bytes < 1048576 ? Math.max(1, Math.round(bytes / 1024)) + ' KB' : (bytes / 1048576).toFixed(1) + ' MB'; }
  var activeProfileCountry = 'usa';
  async function loadProfiles(country) { activeProfileCountry = country || activeProfileCountry; var status = document.getElementById('profileStatus'); status.textContent = 'Loading images...'; var response = await fetch('/api/admin/profiles?country=' + activeProfileCountry, { headers: authHeaders() }), custom = {}; if (response.ok) (await response.json()).images.forEach(function (row) { custom[row.slot] = row.image_data; }); document.getElementById('profileGrid').innerHTML = Array.from({ length: 16 }, function (_, i) { var slot = i + 1, fallbackId = ((['usa','uk','canada','germany'].indexOf(activeProfileCountry) * 16) + i) % 100, src = custom[slot] || 'https://randomuser.me/api/portraits/women/' + fallbackId + '.jpg'; return '<article class="profile-image-card"><img src="' + src + '" alt="Profile ' + slot + '"><span>Image ' + slot + '</span><input type="file" accept="image/*" data-slot="' + slot + '" hidden><button type="button" class="replace-image">Replace Image</button></article>'; }).join(''); status.textContent = '16 images'; }
  async function uploadProfile(slot, file) { if (!file) return; var reader = new FileReader(), status = document.getElementById('profileStatus'); status.textContent = 'Uploading...'; reader.onload = async function () { var response = await fetch('/api/admin/profiles', { method: 'POST', headers: Object.assign({ 'Content-Type': 'application/json' }, authHeaders()), body: JSON.stringify({ country: activeProfileCountry, slot: slot, image: reader.result }) }); if (response.ok) loadProfiles(); else status.textContent = 'Upload failed. Use an image under 1 MB.'; }; reader.readAsDataURL(file); }
  async function loadVideos() { var list = document.getElementById('videoList'); var response = await fetch('/api/admin/videos', { headers: authHeaders(), cache: 'no-store' }); if (!response.ok) { list.innerHTML = '<p class="empty">Could not load videos.</p>'; return; } var videos = (await response.json()).videos || []; list.innerHTML = videos.length ? videos.map(function (video) { return '<article class="video-card"><video controls muted preload="metadata" src="/api/public/video?id=' + Number(video.id) + '"></video><strong title="' + escapeHtml(video.file_name) + '">' + escapeHtml(video.file_name) + '</strong><small>' + formatBytes(Number(video.size_bytes)) + ' · ' + new Date(video.created_at).toLocaleDateString() + '</small><button type="button" data-delete-video="' + Number(video.id) + '">Remove video</button></article>'; }).join('') : '<p class="empty">No videos uploaded yet.</p>'; }
  async function uploadVideo(file) { var status = document.getElementById('videoStatus'); if (!file) return; if (file.size > 104857600) { status.textContent = 'Video must be 100 MB or smaller.'; return; } status.textContent = 'Uploading ' + file.name + '…'; var form = new FormData(); form.append('video', file); var response = await fetch('/api/admin/videos', { method: 'POST', headers: authHeaders(), body: form }); if (response.ok) { document.getElementById('videoFile').value = ''; status.textContent = 'Video uploaded.'; loadVideos(); } else { status.textContent = await response.text() || 'Upload failed.'; } }
  async function deleteVideo(id) { if (!window.confirm('Remove this video permanently?')) return; var status = document.getElementById('videoStatus'); status.textContent = 'Removing…'; var response = await fetch('/api/admin/videos?id=' + encodeURIComponent(id), { method: 'DELETE', headers: authHeaders() }); status.textContent = response.ok ? 'Video removed.' : 'Could not remove video.'; if (response.ok) loadVideos(); }
  async function load() { if (!token || !username) return; var range = document.getElementById('range').value; var query = '/api/admin/analytics?range=' + range + '&tzOffset=' + new Date().getTimezoneOffset(); var response = await fetch(query, { headers: authHeaders(), cache: 'no-store' }); if (response.status === 401) { sessionStorage.removeItem('cml_admin_token'); sessionStorage.removeItem('cml_admin_username'); token = ''; username = ''; showLogin('Invalid username or password.'); return; } if (!response.ok) throw new Error('Could not load analytics (' + response.status + ').'); var data = await response.json(); document.getElementById('liveCount').textContent = data.liveVisitors.toLocaleString(); document.getElementById('pageviews').textContent = data.pageviews.toLocaleString(); document.getElementById('updated').textContent = 'Updated ' + new Date(data.generatedAt).toLocaleString(); renderTimeline(data.timeline); renderCountries(data.countries); renderList('sources', data.sources); renderList('devices', data.devices || []); renderList('browsers', data.browsers || []); renderLive(data.live); }
  function showLogin(message) { dashboard.hidden = true; login.hidden = false; document.getElementById('loginError').textContent = message || ''; }
  function showDashboard() { login.hidden = true; dashboard.hidden = false; load().catch(function (error) { document.getElementById('updated').textContent = error.message; }); loadProfiles().catch(function () {}); loadVideos().catch(function () {}); }
  document.getElementById('loginForm').addEventListener('submit', function (event) { event.preventDefault(); username = document.getElementById('username').value; token = document.getElementById('token').value; sessionStorage.setItem('cml_admin_username', username); sessionStorage.setItem('cml_admin_token', token); showDashboard(); });
  document.getElementById('range').addEventListener('change', function () { load().catch(function (e) { alert(e.message); }); }); document.getElementById('refresh').addEventListener('click', function () { load().catch(function (e) { alert(e.message); }); });
  Array.prototype.forEach.call(document.querySelectorAll('[data-panel]'), function (button) { button.addEventListener('click', function () { var panel = button.getAttribute('data-panel'); Array.prototype.forEach.call(document.querySelectorAll('.dashboard-panel'), function (item) { item.hidden = item.id !== panel; }); Array.prototype.forEach.call(document.querySelectorAll('[data-panel]'), function (item) { item.classList.toggle('active', item === button); }); if (panel === 'videos') loadVideos().catch(function () {}); }); });
  document.getElementById('logout').addEventListener('click', function () { sessionStorage.removeItem('cml_admin_token'); sessionStorage.removeItem('cml_admin_username'); token = ''; username = ''; showLogin(); });
  document.getElementById('profileCountries').addEventListener('click', function (e) { var b = e.target.closest('[data-country]'); if (!b) return; Array.prototype.forEach.call(document.querySelectorAll('#profileCountries button'), function (x) { x.classList.toggle('active', x === b); }); loadProfiles(b.getAttribute('data-country')); });
  document.getElementById('profileGrid').addEventListener('click', function (e) { var b = e.target.closest('.replace-image'); if (b) b.parentNode.querySelector('input').click(); }); document.getElementById('profileGrid').addEventListener('change', function (e) { if (e.target.type === 'file') uploadProfile(Number(e.target.getAttribute('data-slot')), e.target.files[0]); });
  document.getElementById('videoUploadForm').addEventListener('submit', function (event) { event.preventDefault(); uploadVideo(document.getElementById('videoFile').files[0]).catch(function () { document.getElementById('videoStatus').textContent = 'Upload failed.'; }); }); document.getElementById('videoList').addEventListener('click', function (event) { var button = event.target.closest('[data-delete-video]'); if (button) deleteVideo(button.getAttribute('data-delete-video')).catch(function () { document.getElementById('videoStatus').textContent = 'Could not remove video.'; }); });
  if (token) showDashboard(); setInterval(function () { if (token && !dashboard.hidden) load().catch(function () {}); }, 30000);
}());
